name:                html-validator-cli
version:             0.1.0.5
github:              "iij-ii/html-validator-cli"
license:             BSD3
author:              "Kenzo Yotsuya"
maintainer:          "kyotsuya@iij-ii.co.jp"
copyright:           "IIJ Innovation Institute Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A command-line interface for https://validator.w3.org/
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iij-ii/html-validator-cli#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- ansi-terminal
- bytestring
- directory >= 1.2.5
- doctest
- filepath
- http-conduit
- hspec
- text
- utf8-string

library:
  source-dirs: src

executables:
  validatehtml:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - html-validator-cli

tests:
  html-validator-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - html-validator-cli

  html-validator-cli-doctest:
    main:                doctest-driver.hs
    source-dirs:         test/doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - html-validator-cli

data-dir: test/data
data-files:
- "*.json"
- "*.txt"
