version: 2
jobs:
  build:
    docker:
      - image: haskell:8.0
    steps:
      - checkout
      - run:
          name: Upgrade Stack
          command: stack upgrade
      - run:
          name: Run test
          command: stack test
